[2022-05-11 15:00:47,414] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 15:00:47,415] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 15:00:47,416] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 15:00:47,417] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 15:00:47,418] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 15:00:47,419] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-05-11 15:00:49,453] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EAC3A50C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 15:00:49,454] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EAC3A50C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 15:00:49,455] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 15:00:49,456] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 15:00:49,457] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 16:27:38,863] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 16:27:38,864] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 16:27:38,864] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 16:27:38,865] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 16:27:38,866] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 16:27:38,866] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-05-11 16:27:40,912] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000241DC624548>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 16:27:40,912] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000241DC624548>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 16:27:40,913] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 16:27:40,914] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 16:27:40,915] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 16:29:14,639] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 16:29:14,640] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 16:29:14,641] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 16:29:14,641] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 16:29:14,642] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type":"application/json;charset=UTF-8","Authorization":"BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 16:29:14,643] [log.py|__console] [line:37] INFO    : 请求体:"{\"channel\":\"whatsapp\",\"to\":\"85259842833\",\"whatsapp\":{\"type\":\"text\",\"text\":{\"body\":\"测试\"},\"preview_url\":false}}"
[2022-05-11 16:29:14,646] [log.py|__console] [line:43] ERROR   : 'str' object has no attribute 'items'
[2022-05-11 16:29:14,647] [log.py|__console] [line:43] ERROR   : 'str' object has no attribute 'items'
[2022-05-11 16:29:14,647] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 16:29:14,648] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 16:29:14,649] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 16:32:57,652] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 16:32:57,653] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 16:32:57,654] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 16:32:57,655] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 16:32:57,655] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 16:32:57,656] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-05-11 16:32:59,673] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000241DDCAF648>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 16:32:59,674] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000241DDCAF648>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 16:32:59,674] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 16:32:59,675] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 16:32:59,676] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 17:25:01,921] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 17:25:01,922] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 17:25:01,923] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 17:25:01,923] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 17:25:01,924] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 17:25:01,925] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-05-11 17:25:03,947] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAA75F8248>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 17:25:03,948] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAA75F8248>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 17:25:03,948] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 17:25:03,949] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 17:25:03,950] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 17:25:35,726] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 17:25:35,727] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 17:25:35,728] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 17:25:35,730] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 17:25:35,732] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type":"application/json;charset=UTF-8","Authorization":"BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 17:25:35,733] [log.py|__console] [line:37] INFO    : 请求体:"{\"channel\":\"whatsapp\",\"to\":\"85259842833\",\"whatsapp\":{\"type\":\"text\",\"text\":{\"body\":\"测试\"},\"preview_url\":false}}"
[2022-05-11 17:25:35,738] [log.py|__console] [line:43] ERROR   : 'str' object has no attribute 'items'
[2022-05-11 17:25:35,740] [log.py|__console] [line:43] ERROR   : 'str' object has no attribute 'items'
[2022-05-11 17:25:35,742] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 17:25:35,744] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 17:25:35,745] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 17:26:06,674] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 17:26:06,674] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 17:26:06,675] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 17:26:06,676] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 17:26:06,677] [log.py|__console] [line:37] INFO    : 请求头:"{\"Content-Type\":\"application/json;charset=UTF-8\",\"Authorization\":\"BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ==\"}"
[2022-05-11 17:26:06,677] [log.py|__console] [line:37] INFO    : 请求体:"\"{\\\"channel\\\":\\\"whatsapp\\\",\\\"to\\\":\\\"85259842833\\\",\\\"whatsapp\\\":{\\\"type\\\":\\\"text\\\",\\\"text\\\":{\\\"body\\\":\\\"测试\\\"},\\\"preview_url\\\":false}}\""
[2022-05-11 17:26:06,682] [log.py|__console] [line:43] ERROR   : 'str' object has no attribute 'items'
[2022-05-11 17:26:06,683] [log.py|__console] [line:43] ERROR   : 'str' object has no attribute 'items'
[2022-05-11 17:26:06,683] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 17:26:06,684] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 17:26:06,685] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 17:26:29,114] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 17:26:29,116] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 17:26:29,118] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 17:26:29,120] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 17:26:29,122] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 17:26:29,123] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-05-11 17:26:31,160] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018C620D17C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 17:26:31,162] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018C620D17C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 17:26:31,163] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 17:26:31,165] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 17:26:31,166] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-05-11 17:26:37,575] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-11 17:26:37,577] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-11 17:26:37,578] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-11 17:26:37,580] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-11 17:26:37,582] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-11 17:26:37,583] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-05-11 17:26:39,618] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018C5F0AF148>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 17:26:39,620] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018C5F0AF148>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-11 17:26:39,622] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-11 17:26:39,623] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-11 17:26:39,625] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
