[2022-05-09 15:37:19,222] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-05-09 15:37:19,223] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-05-09 15:37:19,223] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-05-09 15:37:19,224] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-05-09 15:37:19,225] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-05-09 15:37:19,226] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-05-09 15:37:21,266] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274CEE233C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-09 15:37:21,267] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274CEE233C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-05-09 15:37:21,268] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-05-09 15:37:21,268] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-05-09 15:37:21,269] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
