[2022-04-21 16:16:35,519] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-21 16:16:35,520] [log.py|__console] [line:37] INFO    : 标题:ds
[2022-04-21 16:16:35,521] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-21 16:16:35,521] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-21 16:16:35,522] [log.py|__console] [line:37] INFO    : 请求头:
[2022-04-21 16:16:35,523] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-21 16:16:37,588] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023653B5FB88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-21 16:16:37,590] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023653B5FB88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-21 16:16:37,590] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-21 16:16:37,591] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-21 16:16:37,592] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
