[2022-01-09 16:21:53,245] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:21:53,246] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:21:53,247] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:21:53,248] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:21:53,248] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:21:53,249] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:22:02,135] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:22:02,136] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:22:02,136] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:22:02,137] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:22:02,138] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:22:02,138] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:22:14,365] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217DA2884C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:22:14,366] [log.py|__console] [line:37] INFO    : 获取响应失败，请检查
[2022-01-09 16:22:14,367] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-01-09 16:22:14,367] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-01-09 16:22:23,153] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217DA333BC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:22:23,154] [log.py|__console] [line:37] INFO    : 获取响应失败，请检查
[2022-01-09 16:22:23,155] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-01-09 16:22:23,155] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-01-09 16:25:12,375] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:25:12,377] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:25:12,379] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:25:12,381] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:25:12,382] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:25:12,384] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:25:28,625] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:25:28,626] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:25:28,627] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:25:28,628] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:25:28,628] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:25:28,629] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:26:05,832] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013A6993FC08>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:26:15,406] [log.py|__console] [line:43] ERROR   : 'ConnectionError' object has no attribute 'status_code'
[2022-01-09 16:26:15,406] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-01-09 16:26:15,407] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-01-09 16:26:35,618] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:26:35,619] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:26:35,620] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:26:35,621] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:26:35,621] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:26:35,622] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:26:42,483] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:26:42,484] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:26:42,485] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:26:42,485] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:26:42,486] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:26:42,487] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:27:12,888] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B397741448>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:29:02,705] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:29:02,707] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:29:02,708] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:29:02,710] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:29:02,711] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:29:02,713] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:29:23,753] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B2057EFC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:30:18,952] [log.py|__console] [line:43] ERROR   : 'ConnectionError' object has no attribute 'status_code'
[2022-01-09 16:30:18,954] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-01-09 16:30:18,955] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-01-09 16:30:42,358] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:30:42,360] [log.py|__console] [line:37] INFO    : 标题:linda test
[2022-01-09 16:30:42,361] [log.py|__console] [line:37] INFO    : url:http://172.30.22.167:7003/n/callback/updateStatusToCSMSReq
[2022-01-09 16:30:42,363] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:30:42,365] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json"}
[2022-01-09 16:30:42,367] [log.py|__console] [line:37] INFO    : 请求体:{"ID1":"2021101300158","ID2":"CS211014002002","ID3":"2021101401","status1":4,"inputBaseMessage":{"apiName":"updateStatusToCSMSReq","apiVersion":"1.0","systemModel":"QUOTE_STATUS_UPDATE","reqWho":"csr","systemChannel":"CSMS"}}
[2022-01-09 16:31:05,607] [log.py|__console] [line:37] INFO    : 响应码:404
[2022-01-09 16:31:05,610] [log.py|__console] [line:37] INFO    : 响应头:{"Content-Type": "application/json;charset=UTF-8", "Transfer-Encoding": "chunked", "Content-Encoding": "gzip", "Vary": "Accept-Encoding", "Date": "Sun, 09 Jan 2022 08:30:10 GMT"}
[2022-01-09 16:31:05,612] [log.py|__console] [line:37] INFO    : 响应内容:{"timestamp": 1641717010650, "status": 404, "error": "Not Found", "message": "No message available", "path": "/n/callback/updateStatusToCSMSReq"}
[2022-01-09 16:31:05,614] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-01-09 16:31:05,615] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-01-09 16:31:34,630] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:31:34,631] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:31:34,633] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:31:34,634] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:31:34,635] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:31:34,637] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:31:55,668] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028FD06CAD08>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:32:03,771] [log.py|__console] [line:37] INFO    : 获取响应失败，请检查
[2022-01-09 16:32:09,554] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-01-09 16:32:09,555] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-01-09 16:33:02,434] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:33:02,435] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:33:02,436] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:33:02,437] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:33:02,438] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:33:02,439] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:33:06,829] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-01-09 16:33:06,830] [log.py|__console] [line:37] INFO    : 标题:test
[2022-01-09 16:33:06,831] [log.py|__console] [line:37] INFO    : url:http://172.25.171.31:7003/soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq
[2022-01-09 16:33:06,832] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-01-09 16:33:06,832] [log.py|__console] [line:37] INFO    : 请求头:
[2022-01-09 16:33:06,833] [log.py|__console] [line:37] INFO    : 请求体:{"accountNo":98784,"isConfirmed":false,"inputBaseMessage":{"apiName":"GetImageBillListReq","apiVersion":"1.0","systemModel":"WeChatOa","requestId":"GetImageBillListReq_d73f0f8e","reqWho":"WeChatOa","systemChannel":"CSMS"}}
[2022-01-09 16:33:27,852] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8BBB79808>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:33:27,853] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.25.171.31', port=7003): Max retries exceeded with url: /soa-infra/resources/default/UniverseOne/APIRequest/GetImageBillListReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8BBB79808>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-01-09 16:33:27,854] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-01-09 16:33:27,854] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-01-09 16:33:27,855] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
