[2022-06-13 13:43:15,399] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 147, in add_apiTestcase
    param_encrypt_type = data['encrypt_value']
KeyError: 'encrypt_value'

[2022-06-13 13:43:18,337] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 178, in edit_apiTestcase
    param_encrypt_type = data['encrypt_value']
KeyError: 'encrypt_value'

[2022-06-13 13:43:28,971] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 181, in edit_apiTestcase
    param_id = data['id']
KeyError: 'id'

[2022-06-13 14:29:14,763] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 348, in debugApi
    return jsonify(output)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "D:\ProgramFiles(x86)\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\PycharmProjects\AutoTest_platform\utils\time.py", line 12, in default
    return JSONEncoder.default(self, obj)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CaseInsensitiveDict is not JSON serializable

[2022-06-13 14:29:33,541] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 348, in debugApi
    return jsonify(output)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "D:\ProgramFiles(x86)\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\PycharmProjects\AutoTest_platform\utils\time.py", line 12, in default
    return JSONEncoder.default(self, obj)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CaseInsensitiveDict is not JSON serializable

[2022-06-13 14:30:19,651] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 348, in debugApi
    return jsonify(output)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "D:\ProgramFiles(x86)\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\PycharmProjects\AutoTest_platform\utils\time.py", line 12, in default
    return JSONEncoder.default(self, obj)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CaseInsensitiveDict is not JSON serializable

[2022-06-13 14:31:08,642] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 348, in debugApi
    return jsonify(output)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "D:\ProgramFiles(x86)\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\PycharmProjects\AutoTest_platform\utils\time.py", line 12, in default
    return JSONEncoder.default(self, obj)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CaseInsensitiveDict is not JSON serializable

[2022-06-13 14:33:23,088] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 64, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\apiTest\apiTestcaseView.py", line 348, in debugApi
    return jsonify(output)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "D:\ProgramFiles(x86)\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\PycharmProjects\AutoTest_platform\utils\time.py", line 12, in default
    return JSONEncoder.default(self, obj)
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "D:\ProgramFiles(x86)\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CaseInsensitiveDict is not JSON serializable

