[2022-05-17 17:38:13,956] [log.py|__console] [line:43] ERROR   : Traceback (most recent call last):
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\AutoTest_platform\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\AutoTest_platform\utils\tokenUtil.py", line 84, in wrapper
    return func(*args, **kw)
  File "D:\PycharmProjects\AutoTest_platform\views\submittedTests\submittedTestsManagementView.py", line 97, in get_reason_option
    output = {'code': 1000, 'data': ast.literal_eval(reason_option.value), 'success': True}
AttributeError: 'NoneType' object has no attribute 'value'

