[2022-04-14 15:20:03,609] [log.py|__console] [line:37] INFO    : whatsapp API
[2022-04-14 15:20:03,610] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,609] [log.py|__console] [line:37] INFO    : whatsapp API
[2022-04-14 15:20:03,610] [log.py|__console] [line:37] INFO    : test
[2022-04-14 15:20:03,611] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,610] [log.py|__console] [line:37] INFO    : test
[2022-04-14 15:20:03,612] [log.py|__console] [line:37] INFO    : 测试一下
[2022-04-14 15:20:03,612] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,612] [log.py|__console] [line:37] INFO    : 测试一下
[2022-04-14 15:20:03,622] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:03,623] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,622] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:03,624] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-04-14 15:20:03,624] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,624] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-04-14 15:20:03,625] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-14 15:20:03,625] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,625] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-14 15:20:03,625] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:03,626] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,625] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:03,626] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-04-14 15:20:03,626] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,626] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-04-14 15:20:03,627] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-14 15:20:03,627] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:03,627] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-14 15:20:05,658] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB35F508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:05,658] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,658] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB35F508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:05,659] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB35F508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:05,659] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,659] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB35F508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:05,659] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:05,660] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,659] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:05,660] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:05,660] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,660] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:05,661] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-14 15:20:05,661] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,661] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-14 15:20:05,711] [log.py|__console] [line:37] INFO    : whatsapp API
[2022-04-14 15:20:05,711] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,711] [log.py|__console] [line:37] INFO    : whatsapp API
[2022-04-14 15:20:05,711] [log.py|__console] [line:37] INFO    : test
[2022-04-14 15:20:05,712] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,711] [log.py|__console] [line:37] INFO    : test
[2022-04-14 15:20:05,712] [log.py|__console] [line:37] INFO    : tt
[2022-04-14 15:20:05,712] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,712] [log.py|__console] [line:37] INFO    : tt
[2022-04-14 15:20:05,717] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:05,718] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,717] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:05,718] [log.py|__console] [line:37] INFO    : 标题:tt
[2022-04-14 15:20:05,718] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,718] [log.py|__console] [line:37] INFO    : 标题:tt
[2022-04-14 15:20:05,719] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-14 15:20:05,719] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,719] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-14 15:20:05,720] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:05,720] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,720] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:05,720] [log.py|__console] [line:37] INFO    : 请求头:
[2022-04-14 15:20:05,721] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,720] [log.py|__console] [line:37] INFO    : 请求头:
[2022-04-14 15:20:05,721] [log.py|__console] [line:37] INFO    : 请求体:
[2022-04-14 15:20:05,721] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:05,721] [log.py|__console] [line:37] INFO    : 请求体:
[2022-04-14 15:20:07,733] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB391A08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:07,733] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,733] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB391A08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:07,734] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB391A08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:07,734] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,734] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB391A08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:07,734] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:07,735] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,734] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:07,736] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:07,736] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,736] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:07,737] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-14 15:20:07,737] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,737] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-14 15:20:07,868] [log.py|__console] [line:37] INFO    : whatsapp API
[2022-04-14 15:20:07,869] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,868] [log.py|__console] [line:37] INFO    : whatsapp API
[2022-04-14 15:20:07,869] [log.py|__console] [line:37] INFO    : test
[2022-04-14 15:20:07,870] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,869] [log.py|__console] [line:37] INFO    : test
[2022-04-14 15:20:07,870] [log.py|__console] [line:37] INFO    : tt2
[2022-04-14 15:20:07,871] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,870] [log.py|__console] [line:37] INFO    : tt2
[2022-04-14 15:20:07,876] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:07,876] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,876] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:07,877] [log.py|__console] [line:37] INFO    : 标题:tt2
[2022-04-14 15:20:07,877] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,877] [log.py|__console] [line:37] INFO    : 标题:tt2
[2022-04-14 15:20:07,877] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-14 15:20:07,878] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,877] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-14 15:20:07,878] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:07,878] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,878] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:07,879] [log.py|__console] [line:37] INFO    : 请求头:
[2022-04-14 15:20:07,879] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,879] [log.py|__console] [line:37] INFO    : 请求头:
[2022-04-14 15:20:07,879] [log.py|__console] [line:37] INFO    : 请求体:
[2022-04-14 15:20:07,880] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:07,879] [log.py|__console] [line:37] INFO    : 请求体:
[2022-04-14 15:20:09,888] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB3A07C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:09,888] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,888] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB3A07C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:09,889] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB3A07C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:09,889] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,889] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252BB3A07C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-14 15:20:09,890] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:09,890] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,890] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:09,890] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:09,891] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,890] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:09,892] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-14 15:20:09,892] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,892] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-14 15:20:09,932] [log.py|__console] [line:37] INFO    : test2
[2022-04-14 15:20:09,932] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,932] [log.py|__console] [line:37] INFO    : test2
[2022-04-14 15:20:09,933] [log.py|__console] [line:37] INFO    : ttt
[2022-04-14 15:20:09,933] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,933] [log.py|__console] [line:37] INFO    : ttt
[2022-04-14 15:20:09,933] [log.py|__console] [line:37] INFO    : qwe
[2022-04-14 15:20:09,934] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,933] [log.py|__console] [line:37] INFO    : qwe
[2022-04-14 15:20:09,938] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:09,940] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,938] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-14 15:20:09,941] [log.py|__console] [line:37] INFO    : 标题:qwe
[2022-04-14 15:20:09,941] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,941] [log.py|__console] [line:37] INFO    : 标题:qwe
[2022-04-14 15:20:09,941] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/media
[2022-04-14 15:20:09,941] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,941] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/media
[2022-04-14 15:20:09,942] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:09,942] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,942] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-14 15:20:09,943] [log.py|__console] [line:37] INFO    : 请求头:
[2022-04-14 15:20:09,943] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,943] [log.py|__console] [line:37] INFO    : 请求头:
[2022-04-14 15:20:09,943] [log.py|__console] [line:37] INFO    : 文件名:TCZ - 软件开发体系 - 代码开发规范 v0.3 (28-Jun-2018).docx，後臺文件名:862fa8fe174a40bca170484d30ebdf63.docx
[2022-04-14 15:20:09,944] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,943] [log.py|__console] [line:37] INFO    : 文件名:TCZ - 软件开发体系 - 代码开发规范 v0.3 (28-Jun-2018).docx，後臺文件名:862fa8fe174a40bca170484d30ebdf63.docx
[2022-04-14 15:20:09,944] [log.py|__console] [line:37] INFO    : 请求体:
[2022-04-14 15:20:09,944] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,944] [log.py|__console] [line:37] INFO    : 请求体:
[2022-04-14 15:20:09,945] [log.py|__console] [line:43] ERROR   : [Errno 2] No such file or directory: 'd:\\pycharmprojects\\autotest_platform\\updateFiles/apiTest\\862fa8fe174a40bca170484d30ebdf63.docx'
[2022-04-14 15:20:09,945] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,945] [log.py|__console] [line:43] ERROR   : [Errno 2] No such file or directory: 'd:\\pycharmprojects\\autotest_platform\\updateFiles/apiTest\\862fa8fe174a40bca170484d30ebdf63.docx'
[2022-04-14 15:20:09,945] [log.py|__console] [line:43] ERROR   : [Errno 2] No such file or directory: 'd:\\pycharmprojects\\autotest_platform\\updateFiles/apiTest\\862fa8fe174a40bca170484d30ebdf63.docx'
[2022-04-14 15:20:09,946] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,945] [log.py|__console] [line:43] ERROR   : [Errno 2] No such file or directory: 'd:\\pycharmprojects\\autotest_platform\\updateFiles/apiTest\\862fa8fe174a40bca170484d30ebdf63.docx'
[2022-04-14 15:20:09,946] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:09,946] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,946] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-14 15:20:09,947] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:09,947] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,947] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-14 15:20:09,947] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-14 15:20:09,948] [log.py|write] [line:232] WARNING : [2022-04-14 15:20:09,947] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
